namespace Vanadium.enums
{
    // NAMJIIGMBJO
    // all the deprecated shit is broken on 2024-2026 and i think they remove them
    public enum GiftType
    {
        None = -1,
        Default,
        First_Activity,
        Game_Drop,
        All_Daily_Challenges_Complete,
        All_Weekly_Challenge_Complete,
        Daily_Challenge_Complete,
        Weekly_Challenge_Complete,
        Unassigned_Equipment = 10,
        Unassigned_Avatar,
        Unassigned_Consumable,
        Reacquisition = 20,
        Membership,
        NUX_TokensAndDressUp = 30,
        NUX_Experiment1,
        NUX_Experiment2,
        NUX_Experiment3,
        NUX_Experiment4,
        NUX_Experiment5,
        GameRewards = 50,
        GameRewards_Tokens,
        GameRewards_Tokens_Experiment_Override,
        LevelUp = 100,
        Purchased_Gift_A = 500,
        Purchased_Gift_B,
        Purchased_Gift_C,
        Purchased_Gift_D,
        Holiday = 1000,
        Contest,
        Promotion,
        LimitedTime,
        LimitedTimeEvent,
        Deprecated = 1100,
        RecRoyale = 1200,
        Friendotron_Gift = 1300,
        DEPRECATED_Paintball_ClearCut = 2000,
        DEPRECATED_Paintball_Homestead,
        DEPRECATED_Paintball_Quarry,
        DEPRECATED_Paintball_River,
        DEPRECATED_Paintball_Dam,
        DEPRECATED_Paintball_DriveIn,
        Paintball_ClearCut = 2010,
        Paintball_Homestead,
        Paintball_Quarry,
        Paintball_River,
        Paintball_Dam,
        Paintball_DriveIn,
        DEPRECATED_Discgolf_Propulsion = 3000,
        DEPRECATED_Discgolf_Lake,
        Discgolf_Propulsion = 3010,
        Discgolf_Lake,
        Discgolf_Mode_CoopCatch = 3500,
        Quest_Goblin_A = 4000,
        Quest_Goblin_B,
        Quest_Goblin_C,
        Quest_Goblin_S,
        Quest_Goblin_Consumable,
        Quest_Cauldron_A = 4010,
        Quest_Cauldron_B,
        Quest_Cauldron_C,
        Quest_Cauldron_S,
        Quest_Cauldron_Consumable,
        Quest_Pirate1_A = 4100,
        Quest_Pirate1_B,
        Quest_Pirate1_C,
        Quest_Pirate1_S,
        Quest_Pirate1_X,
        Quest_Pirate1_Consumable,
        Quest_Dracula1_A = 4200,
        Quest_Dracula1_B,
        Quest_Dracula1_C,
        Quest_Dracula1_S,
        Quest_Dracula1_X,
        Quest_Dracula1_Consumable,
        Quest_Dracula1_SS,
        Quest_SciFi_A = 4500,
        Quest_SciFi_B,
        Quest_SciFi_C,
        Quest_SciFi_S,
        Quest_Scifi_Consumable,
        DEPRECATED_Charades = 5000,
        Charades,
        DEPRECATED_Soccer = 6000,
        Soccer,
        DEPRECATED_Paddleball = 7000,
        Paddleball,
        DEPRECATED_Dodgeball = 8000,
        Dodgeball,
        DEPRECATED_Lasertag = 9000,
        Lasertag,
        DEPRECATED_Bowling = 10000,
        Bowling,
        StuntRunner_TheMainEvent_A = 11000,
        StuntRunner_TheMainEvent_B,
        StuntRunner_TheMainEvent_C,
        StuntRunner_TheMainEvent_D,
        StuntRunner_TheMainEvent_S,
        StuntRunner_TheMainEvent_X,
        StuntRunner_TheMainEvent_Consumable,
        StuntRunner_TheMainEvent_SS,
        RecRally = 12000,
        Showdown_A = 12100,
        Showdown_B,
        Showdown_C,
        ProgressionEvent = 13000,
        Store_LaserTag = 100000,
        Store_RecCenter = 100010,
        Consumable = 110000,
        Token = 110100,
        Punchcard_Challenge_Complete = 110200,
        All_Punchcard_Challenges_Complete,
        New_Player_Checklist_Item_Complete = 110300,
        Commerce_Purchase = 200000,
        Gift_Card_Redemption = 210000
    }
}